### ISSUE TITLE
Java program running out of memory

### ISSUE THREAD

**Issue by gsaqui** [antonwierenga/docker-activemq-jmx#2]
Sometimes when I run the container for long periods of time the jvm inside of the container runs out of memory.  Any idea how I can stop that from happening?

**Comment by antonwierenga** [comment]
You can try increasing the memory. You need to update the docker-active-jmx dockerfile for this; ACTIVEMQ_OPTS is currently not an environment variable in the docker file. Once you've declared ACTIVEMQ_OPTS as an environment variable and build the docker you can specify the memory settings. See [here](https://stackoverflow.com/questions/59617405/how-can-i-increase-the-heap-memory-for-activemq-inside-a-docker-image
) for an example.

To see what is causing the out of memory errors you need a Java memory profiler and analyse what objects are using so much memory.
